"""Add total_amount column to orders

Revision ID: 9b93aeed70c5
Revises: 296af24efed3
Create Date: 2024-12-20 09:24:46.278812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b93aeed70c5'
down_revision = '296af24efed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
